# Generated by Django 5.2.1 on 2025-05-31 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_cuerpo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MedicionCuerpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_medicion', models.DateTimeField(auto_now_add=True)),
                ('ancho_hombros', models.FloatField(blank=True, null=True)),
                ('ancho_caderas', models.FloatField(blank=True, null=True)),
                ('icc_estimado', models.FloatField(blank=True, null=True)),
                ('relacion_hombro_cintura', models.FloatField(blank=True, null=True)),
                ('tipo_cuerpo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_cuerpo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
