# Generated by Django 5.2.1 on 2025-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_usuario_fecha_nacimiento_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'), # Asegúrate de tener esto si tu migración anterior lo tiene
    ]

    operations = [
        # migrations.AddField(
        #     model_name='usuario',
        #     name='celular',
        #     field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='ciudad',
        #     field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='direccion',
        #     field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='foto_cuerpo_1',
        #     field=models.ImageField(blank=True, null=True, upload_to='body_photos/', verbose_name='Foto de Cuerpo 1'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='foto_cuerpo_2',
        #     field=models.ImageField(blank=True, null=True, upload_to='body_photos/', verbose_name='Foto de Cuerpo 2'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='foto_cuerpo_3',
        #     field=models.ImageField(blank=True, null=True, upload_to='body_photos/', verbose_name='Foto de Cuerpo 3'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='foto_cuerpo_4',
        #     field=models.ImageField(blank=True, null=True, upload_to='body_photos/', verbose_name='Foto de Cuerpo 4'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='foto_perfil',
        #     field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil'),
        # ),
        # migrations.AddField(
        #     model_name='usuario',
        #     name='pais',
        #     field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        # ),
        # migrations.AlterField(
        #     model_name='usuario',
        #     name='direccion',
        #     field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        # ),
        # migrations.AlterField(
        #     model_name='usuario',
        #     name='email',
        #     field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        # ),
        # migrations.AlterField(
        #     model_name='usuario',
        #     name='first_name',
        #     field=models.CharField(blank=True, max_length=30, verbose_name='Nombre'),
        # ),
        # migrations.AlterField(
        #     model_name='usuario',
        #     name='groups',
        #     field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuario_set', related_query_name='usuario', to='auth.group', verbose_name='groups'),
        # ),
        # migrations.AlterField(
        #     model_name='usuario',
        #     name='last_name',
        #     field=models.CharField(blank=True, max_length=150, verbose_name='Apellido'),
        # ),
        # migrations.AlterField(
        #     model_name='usuario',
        #     name='user_permissions',
        #     field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuario_permissions_set', related_query_name='usuario_permission', to='auth.permission', verbose_name='user permissions'),
        # ),
    ]