# Generated by Django 5.2.1 on 2025-05-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_remove_usuario_github_id_remove_usuario_google_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_pics/'),
        ),
    ]
