# Generated by Django 5.2.1 on 2025-05-26 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20250526_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='pais',
        ),
    ]
