# Generated by Django 5.2.1 on 2025-06-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0007_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estatura',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='peso',
        ),
        migrations.AddField(
            model_name='medicioncuerpo',
            name='estatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicioncuerpo',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
