# Generated by Django 5.2.1 on 2025-06-11 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_medicioncuerpo_body_photos_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisPostura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio_nombre', models.CharField(help_text='Nombre del ejercicio analizado (ej. curl_biceps)', max_length=100)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('video_original', models.FileField(blank=True, help_text='Archivo del video original subido por el usuario.', null=True, upload_to='analisis_videos/originales/')),
                ('video_procesado', models.FileField(blank=True, help_text='Archivo del video con el análisis de postura (esqueleto, etc.).', null=True, upload_to='analisis_videos/procesados/')),
                ('feedback_texto', models.TextField(blank=True, help_text='Retroalimentación textual sobre la postura y técnica.', null=True)),
                ('puntuacion_postura', models.FloatField(blank=True, help_text='Puntuación numérica de la postura (ej. 0.0 a 1.0, o 1 a 10).', null=True)),
                ('angulos_detectados', models.JSONField(blank=True, help_text='Ángulos y coordenadas clave detectadas en el video (formato JSON).', null=True)),
                ('errores_detectados', models.JSONField(blank=True, help_text='Lista de errores de postura detectados (formato JSON).', null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_posturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis de Postura',
                'verbose_name_plural': 'Análisis de Posturas',
                'ordering': ['-fecha_analisis'],
            },
        ),
    ]
